name: flutter_dialogflow
description: Flutter package for makes it easy to integrate dialogflow and support dialogflow v2
version: 0.1.3
author: Victor Alfonso Rodas Oña <victordevcode@gmail.com>
homepage: https://github.com/VictorRancesCode/flutter_dialogflow

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  googleapis_auth: ^1.1.0

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: ">=2.6.0 <3.0.0"
